// src/lib/components/button/Button.tsx
import { cn } from "../../utils";
import { buttonVariants } from "./button.styles";
import { ButtonProps } from "./button.types";

function Button(props: ButtonProps) {
  return (
    <button
      {...props}
      className={cn(
        buttonVariants({
          variant: props.variant,
          size: props.size,
          rounded: props.rounded,
          width: props.width,
          mode: props.mode,
          className: props.className,
        })
      )}
    />
  );
}

export default Button;

// output/svelte/src/components/Button.svelte
<script lang="ts">
  import { buttonVariants } from "../styles";
  import { ButtonProps } from "../types";
  import { cn } from "../utils";

  export let variant: ButtonProps["variant"];
  export let size: ButtonProps["size"];
  export let rounded: ButtonProps["rounded"];
  export let width: ButtonProps["width"];
  export let className: ButtonProps["className"] = undefined;
</script>

<button
  {...$$props}
  class={cn(
    buttonVariants({
      variant: variant,
      size: size,
      rounded: rounded,
      width: width,
      className: className,
    })
  )}><slot /></button
>
