// output/svelte/src/lib/generators/Button.svelte
<script lang="ts">
  import { buttonVariants } from "../../styles";
  import { ButtonProps } from "../../types";
  import { cn } from "../../utils";

  export let variant: ButtonProps["variant"];
  export let size: ButtonProps["size"];
  export let rounded: ButtonProps["rounded"];
  export let width: ButtonProps["width"];
  export let className: ButtonProps["className"] = undefined;
</script>

<button
  {...$$props}
  class={cn(
    buttonVariants({
      variant: variant,
      size: size,
      rounded: rounded,
      width: width,
      className: className,
    })
  )}><slot /></button
>

// output/react/src/components/Button.tsx
import * as React from "react";
import { buttonVariants } from "../styles";
import { ButtonProps } from "../types";
import { cn } from "../utils";

function Button(props: ButtonProps) {
  return (
    <button
      {...props}
      className={cn(
        buttonVariants({
          variant: props.variant,
          size: props.size,
          rounded: props.rounded,
          width: props.width,
          className: props.className,
        })
      )}
    >
      {props.children}
    </button>
  );
}

export default Button;
